### PR TITLE
Remove ParserService

### PR DESCRIPTION
**Pull request by no-yan**
This PR removes ParserService to make it work without TypeScript parser.

I'm not sure how to handle `AST_NODE_TYPES.JSXMemberExpression` and `AST_NODE_TYPES.ImportNamespaceSpecifier`.
The current behavior is to ignore both.

### CODE REVIEW

**Review by Monchi — COMMENTED** [review]
Thanks for the PR! I understand that this is a draft, but let me some discussion.

Thanks for the PR! I understand that this is a draft, but let me have some discussion.

I considered a similar approach, but I finally choose TypeScript parser. This is because there are many cases to bear in mind.

Namespace Import:
```tsx
import * as Chakra from "@chakra-ui/react"

<Chakra.Box>Hello</Chakra.Box>
```

Alias Import:
```tsx
import { Box as ChakraBox } from "@chakra-ui/react"

<ChakraBox>Hello</ChakraBox>
```

Dynamic Component:
```tsx
Import { Checkbox, Radio } from "@chakra-ui/react"

const Component = isMultiple ? Checkbox : Radio
<Component>Hello</Component>
```
(Dynamic Component is not supported yet)

Dynamic Component is not supported yet. To do that, we need to flow analysis in the near future and it'll be easier with TypeScript.

So my idea is:

1. Use `@typescript-eslint/parser` if parserService is available.
2. If not, use your logic as a fallback.

What do you think?

**Comment by Monchi** [comment]
Also sorry that I accidentally force pushed to master. Please remove 83a42b1 from your branch.

**Comment by no-yan** [comment]
Your explanation is quite reasonable. I agree with your idea.
Or perhaps you don't need to support any parser other than `@typescript-eslint/parser` for now.

**Comment by Monchi** [comment]
@no-yan 

> Or perhaps you don't need to support any parser other than @typescript-eslint/parser for now.

Ok, then freeze this until the time to support espree parser.

BTW I found your `eslint-plugin-chakraui` right now and read `For potensial users` section. It's so surprising that we started the same thing at the almost same time!
I agree with collaboration so can you be a collaborator of this repo? I really appreciate it if I could merge your advanced feature such as multi-line props support.

**Comment by no-yan** [comment]
> I agree with collaboration so can you be a collaborator of this repo?

Yes. I'm really glad you invited me!
My strategy for multi-line support is a kind of ad-hoc with some flaws, but I'd like to sent a PR  in the next couple of days.

**Comment by Monchi** [comment]
@no-yan That's great! I've just sent an invitation. Please take a look.

**Comment by no-yan** [comment]
I think it's easier to recreate the PR when needed rather than keep updating the changes, so I'll close it.

**Pull request closed without merging**
