### PR TITLE
Support sorting elements of same priority

### PR DESCRIPTION
**Pull request by no-yan**
resolves: #12 

This PR enables sorting in same priority.
samePrioritySorting

### Before:
doesn't sort same priorities. 

### After:
Sort same priorities in defined order.
If the props are from Chakra, they will be sorted by index. If not, they will be sorted alphabetically.

### CODE REVIEW

**Review by Monchi — APPROVED** [review]
LGTM!

I think we need to reconsider the order of keys in the same priority.

e.g.
Current:
```
<Box mt="2" mb="2" marginRight="2" />
```

Expected:
```
<Box mt="2" marginRight="2" mb="2" />
```

This can be out of the scope of this PR.

**Comment by Monchi** [comment]
I'm going to publish a new release after this PR merged.

**Comment by no-yan** [comment]
Thank you for LGTM!

> I think we need to reconsider the order of keys in the same priority.
Yes! I think it would be better to do it in another PR.
We need to set a proper direction, such as whether to consider the custom nature of sorting.

**Comment by Monchi** [comment]
Let's discuss in #15

**Pull request merged**
